name: Harpreets Project Work

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: SCP files to remote server
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        scp: |
          ./target/*.war => /tmp/
        first_ssh: |
          ls -lart /tmp
        connect_timeout: 30  # Increase timeout if needed

    - name: Trigger Jenkins Job Via Curl
      run: |
       curl -X POST "http://54.196.172.13:8080/job/TomcatDeployment/build" \
        --user "${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}"
