name: Harpreets Project Work

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
       host: ${{ secrets.HOST }}
       user: ${{ secrets.USERNAME }}
       pass: ${{ secrets.PASSWORD }}
       port: ${{ secrets.PORT }}
       scp: |
        ./target/*.war => /tmp/
       last_ssh: |
        ls -lart /tmp

    - name: Invoke Jenkins Deployment Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://54.196.172.13:8080"
        user: "admin"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "TomcatDeployment"
